version: "3.9"

services:
  api:
    build: .
    container_name: predictive-maintenance-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/maintenance
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      - db
      - mlflow

  db:
    image: postgres:16
    container_name: predictive-maintenance-db
    environment:
      POSTGRES_DB: maintenance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.0
    container_name: predictive-maintenance-mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root file:///mlruns
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow

volumes:
  postgres_data:
  mlflow_data:
